# Generated by Django 3.1.3 on 2020-12-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('contact_address', models.CharField(max_length=50)),
            ],
        ),
    ]
