# Generated by Django 3.1.3 on 2020-12-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
