# Generated by Django 3.1.3 on 2020-12-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app8_1', '0002_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
